from sqlalchemy import Column, ForeignKey, Integer, String, DateTime
from .base import Base
from sqlalchemy.orm import relationship


class Message(Base):
    __tablename__ = "message"

    # sqlite doesnt support uuid so storing the uuid generated by Message pydantic model as string
    uid = Column(String(36), primary_key=True)
    room_id = Column(Integer, ForeignKey("room.id"))
    message = Column(String, nullable=False)
    sent = Column(DateTime)
    sender = Column(Integer, ForeignKey("user.id"))

    room = relationship("Room", back_populates='messages')
    sender_user = relationship("User", back_populates='messages')
